### ISSUE TITLE
windows7 install exe failed

### ISSUE THREAD

**Issue by railwayc** [NeilYXIN/WeRead_mac#1]
error msg
![图片](https://github.com/user-attachments/assets/6e8f1ee7-ea4b-49ea-89a0-cdf64a210aff)

**Comment by railwayc** [comment]
maybe is the compatible problem for windows7.
i google it, and find the same problem https://github.com/desktop/desktop/issues/17209
it is better to add some requirements(eg, windows version) in readme.md

**Comment by NeilYXIN** [comment]
Thanks a lot for your feedback. Electron stopped support for Windows 7 in late 2022.  I've updated the README.
Ref: https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice
