### ISSUE TITLE
1.0.3版本，Windows11，登录后点击分组不能进去

### ISSUE THREAD

**Issue by hookind** [NeilYXIN/WeRead_mac#2]
一个bug，登录后，点击分组不能进去，如下：

https://github.com/user-attachments/assets/61c5c029-ca6f-44f0-a07a-5a9ba9a9725a

**Comment by NeilYXIN** [comment]
感谢关注和发现bug。在macOS上将electron的user agent设置为模拟chrome后问题解决，mac和windows的安装包已上传到 [v1.0.4 pre-release](https://github.com/NeilYXIN/WeRead_Desktop/releases/tag/v1.0.4)，欢迎试用反馈。过几天生成Linux安装包后会正式release新版。
